# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 471b5014d47a087f820fd1255cd1604412364a243f9cfbe0a931418b5ebae8b7f15f718f72cf7988cda70f42dc6db7eccd3438ab1d50fa13ed5371b3916acb38

test:
  secret_key_base: f80265799648134b7846c094134af1d5d8114013b5760d7f13052992acf2ae4bb8096cd96a8547b0a035c8ad7ee22da1cfcd6f190f1580389c9bcf202f19fb88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
